# -*- coding: utf-8 -*-
{
    'name': 'Salon & Beauty Studio Management',
    'version': '19.0.1.0.0',
    'category': 'Operations',
    'summary': 'Appointments, staff availability, packages, commissions and billing for salons and beauty studios',
    'description': 'Salon and beauty studio management module for salon managers, hairdressers and estheticians: manage appointments with staff availability, per-employee schedules, customer cards with service history, prepaid packages and memberships, automatic staff commission calculation and revenue statistics.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account', 'hr', 'product'],
    'data': [
        'security/sf_salon_security.xml',
        'security/ir.model.access.csv',
        'data/sf_salon_sequence.xml',
        'data/sf_salon_cron.xml',
        'data/sf_salon_report.xml',
        'views/sf_salon_service_views.xml',
        'views/sf_salon_staff_views.xml',
        'views/sf_salon_appointment_views.xml',
        'views/sf_salon_package_views.xml',
        'views/sf_salon_commission_views.xml',
        'views/sf_salon_menus.xml',
        'views/report_customer_card.xml',
        'views/report_commissions.xml',
        'views/report_activity.xml',
        'views/res_config_settings_views.xml',
    ],
}
