# -*- coding: utf-8 -*-
{
    'name': 'Utility & Sub-Meter Billing',
    'version': '19.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Delivery points and meters registry, reading campaigns, tiered tariffs and consumption invoices',
    'description': 'Utility and sub-meter billing for water, energy and sub-metering companies: manage delivery points and meters, launch reading campaigns (manual or CSV import), compute consumption per period, apply tiered tariff grids, generate consumption invoices and track abnormal consumption and unpaid invoices.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'uom', 'contacts', 'account'],
    'data': [
        'security/sf_utility_security.xml',
        'security/ir.model.access.csv',
        'data/sf_utility_sequence.xml',
        'data/sf_utility_cron.xml',
        'data/sf_utility_report.xml',
        'views/sf_utility_meter_views.xml',
        'views/sf_utility_reading_views.xml',
        'views/sf_utility_import_wizard_views.xml',
        'views/sf_utility_campaign_views.xml',
        'views/sf_utility_tariff_views.xml',
        'views/sf_utility_invoice_views.xml',
        'views/sf_utility_menus.xml',
        'views/report_reading.xml',
        'views/report_campaign.xml',
        'views/report_invoice.xml',
        'views/report_overdue.xml',
        'views/res_config_settings_views.xml',
    ],
}
