# -*- coding: utf-8 -*-
{
    'name': 'Company Policy & Employee Acknowledgment Register',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Versioned internal policies, employee assignment, acknowledgment sign-off, reminders and coverage rate',
    'description': 'Company policy and employee acknowledgment register: define versioned internal policies (category, version, effective date, owner, content), assign them to employees, publish them to generate acknowledgments, collect the acknowledgment of each employee, compute the coverage rate, raise automatic reminders for pending acknowledgments and for expiring policies, and print PDF reports (policy and acknowledgment register).',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'hr'],
    'data': [
        'security/sf_policy_acknowledgment_security.xml',
        'security/ir.model.access.csv',
        'data/sf_policy_acknowledgment_sequence.xml',
        'data/sf_policy_acknowledgment_cron.xml',
        'data/sf_policy_acknowledgment_report.xml',
        'views/sf_policy_views.xml',
        'views/sf_policy_acknowledgment_views.xml',
        'views/sf_policy_acknowledgment_menus.xml',
        'views/report_policy.xml',
        'views/report_policy_acknowledgment.xml',
        'views/res_config_settings_views.xml',
    ],
}