# -*- coding: utf-8 -*-
{
    'name': 'Production Scheduling Advanced',
    'version': '19.0.1.0.0',
    'category': 'Manufacturing',
    'summary': 'Finite capacity scheduling with Gantt view, bottleneck detection and what-if simulation.',
    'description': 'Production Scheduling Advanced module for Odoo. Finite capacity scheduling with Gantt view, bottleneck detection and what-if simulation.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock', 'mrp'],
    'data': [
        'security/sf_production_scheduling_security.xml',
        'security/ir.model.access.csv',
        'data/sf_production_scheduling_sequence.xml',
        'views/schedule_plan_views.xml',
        'views/schedule_slot_views.xml',
        'views/sf_production_scheduling_menus.xml',
    ],
}
