# -*- coding: utf-8 -*-
{
    'name': 'Laundry & Dry Cleaning Management',
    'version': '19.0.1.0.0',
    'category': 'Operations',
    'summary': 'Deposit vouchers and items, treatment statuses, per-piece pricing, pickup/delivery and customer history',
    'description': 'Laundry and dry cleaning management module for laundromat managers and dry cleaners: manage deposit vouchers with item lists and descriptions, track each item by status (received, in progress, ready, delivered, lost), price per piece by item type and service, handle pickup and delivery with timestamps, and track customer history and overdue items.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account'],
    'data': [
        'security/sf_laundry_security.xml',
        'security/ir.model.access.csv',
        'data/sf_laundry_sequence.xml',
        'data/sf_laundry_cron.xml',
        'data/sf_laundry_report.xml',
        'views/sf_laundry_order_views.xml',
        'views/sf_laundry_item_views.xml',
        'views/sf_laundry_item_type_views.xml',
        'views/sf_laundry_menus.xml',
        'views/report_deposit_receipt.xml',
        'views/report_delivery_ticket.xml',
        'views/report_activity.xml',
        'views/report_overdue_list.xml',
        'views/res_config_settings_views.xml',
    ],
}
