# -*- coding: utf-8 -*-
{
    'name': 'E-commerce Product Reviews & Ratings',
    'version': '18.0.1.0',
    'category': 'Sales',
    'summary': 'Customer product reviews, moderation workflow, verified purchases and aggregated ratings',
    'description': 'Collect, moderate and display product reviews and ratings: customer reviews with rating, title and comment, a moderation workflow (draft, submitted, approved, rejected, archived), verified purchase detection from confirmed sales orders, aggregated average rating and review count per product, and a PDF review summary report.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'product', 'sale', 'contacts'],
    'data': [
        'security/sf_product_reviews_security.xml',
        'security/ir.model.access.csv',
        'data/sf_product_reviews_sequence.xml',
        'data/sf_product_reviews_report.xml',
        'views/sf_product_review_views.xml',
        'views/product_template_views.xml',
        'views/sf_product_reviews_menus.xml',
        'views/report_product_review.xml',
        'views/res_config_settings_views.xml',
    ],
}