# -*- coding: utf-8 -*-
{
    'name': 'Courier & Parcel Delivery Management',
    'version': '18.0.1.0.0',
    'category': 'Operations',
    'summary': 'Pickup/delivery requests, courier assignment, routes, delivery proof (photo/signature), failures, returns and invoicing',
    'description': 'Courier and parcel delivery management module for courier and express delivery companies: register pickup/delivery requests with addresses and time windows, assign couriers, plan routes, track each delivery by status (to collect, in transit, delivered, failed, returned), capture proof of delivery (photo, signature, timestamp), handle delivery failures and returns, and invoice deliveries.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account'],
    'data': [
        'security/sf_courier_security.xml',
        'security/ir.model.access.csv',
        'data/sf_courier_sequence.xml',
        'data/sf_courier_cron.xml',
        'data/sf_courier_report.xml',
        'views/sf_courier_order_views.xml',
        'views/sf_courier_delivery_views.xml',
        'views/sf_courier_route_views.xml',
        'views/sf_courier_menus.xml',
        'views/report_delivery_ticket.xml',
        'views/report_collection_note.xml',
        'views/report_disputes_list.xml',
        'views/report_activity.xml',
        'views/res_config_settings_views.xml',
    ],
}