# -*- coding: utf-8 -*-
{
    'name': 'Rework Management',
    'version': '18.0.1.0',
    'category': 'Manufacturing',
    'summary': 'Track rework orders, operations and scrap with cost computation and escalation alerts',
    'description': 'Rework management for manufacturing and quality departments: create rework orders linked to products and lots, record rework operations with hours, register scrap quantities with values, compute labor cost, scrap value and total rework cost automatically, track orders through draft, in progress, completed, closed and cancelled states, alert managers with a cron when rework orders stay open too long, and print the rework order PDF report.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'product', 'stock', 'contacts'],
    'data': [
        'security/sf_rework_management_security.xml',
        'security/ir.model.access.csv',
        'data/sf_rework_management_sequence.xml',
        'data/sf_rework_management_cron.xml',
        'data/sf_rework_management_report.xml',
        'views/sf_rework_order_views.xml',
        'views/sf_rework_management_menus.xml',
        'views/report_rework_order.xml',
        'views/res_config_settings_views.xml',
    ],
}