# -*- coding: utf-8 -*-
{
    'name': 'Promotional Pricing Engine',
    'version': '19.0.1.0.0',
    'category': 'Sales',
    'summary': 'Time-based promotional pricing with customer segments, volume tiers and margin protection rules.',
    'description': 'Promotional Pricing Engine module for Odoo. Time-based promotional pricing with customer segments, volume tiers and margin protection rules.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_promotional_pricing_engine_security.xml',
        'security/ir.model.access.csv',
        'data/sf_promotional_pricing_engine_sequence.xml',
        'views/promo_rule_views.xml',
        'views/sf_promotional_pricing_engine_menus.xml',
    ],
}
