# -*- coding: utf-8 -*-
{
    'name': 'Parking Lot & Garage Management',
    'version': '18.0.1.0',
    'category': 'Operations',
    'summary': 'Parking sites and zones, spaces, recurring subscriptions, tickets, entry/exit and occupancy statistics',
    'description': 'Parking lot and garage management module for parking operators: manage sites and parking zones, spaces and their occupation, recurring subscriptions (monthly, quarterly, yearly) with invoicing and expiry reminders, tickets and entry/exit with hourly and daily rates, and occupancy and revenue statistics per site.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account'],
    'data': [
        'security/sf_parking_security.xml',
        'security/ir.model.access.csv',
        'data/sf_parking_sequence.xml',
        'data/sf_parking_cron.xml',
        'data/sf_parking_report.xml',
        'views/sf_parking_site_views.xml',
        'views/sf_parking_ticket_views.xml',
        'views/sf_parking_subscription_views.xml',
        'views/sf_parking_report_wizard_views.xml',
        'views/sf_parking_menus.xml',
        'views/report_ticket.xml',
        'views/report_subscription.xml',
        'views/report_revenue.xml',
        'views/report_occupancy.xml',
        'views/res_config_settings_views.xml',
    ],
}