# -*- coding: utf-8 -*-
{
    'name': 'NPS & Customer Feedback',
    'version': '19.0.1.0.0',
    'category': 'Sales',
    'summary': 'NPS survey campaigns with automated detractor follow-up, trend analysis and team scorecards.',
    'description': 'NPS & Customer Feedback module for Odoo. NPS survey campaigns with automated detractor follow-up, trend analysis and team scorecards.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_nps_feedback_security.xml',
        'security/ir.model.access.csv',
        'data/sf_nps_feedback_sequence.xml',
        'views/nps_campaign_views.xml',
        'views/nps_response_views.xml',
        'views/sf_nps_feedback_menus.xml',
    ],
}
