# -*- coding: utf-8 -*-
{
    'name': 'Staffing Agency & Placement',
    'summary': 'Temporary work and placement agency management: candidates, clients, needs, missions, contracts, timesheets and invoicing.',
    'description': 'Manage a temporary work and placement agency end to end: register candidates with profile, skills and availability, record clients and their staffing needs, create missions and mission contracts, track interim worker timesheets, and invoice clients from validated timesheets. Includes daily reminder cron activities, multi-company support, manager-only reserved actions, QWeb reports (mission contract, candidate sheet, mission invoice, activity report) and an agency settings page.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'category': 'Human Resources',
    'version': '19.0.1.0.0',
    'license': 'OPL-1',
    'price': '62.50',
    'currency': 'EUR',
    'application': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account'],
    'data': [
        'security/sf_staffing_security.xml',
        'security/ir.model.access.csv',
        'data/sf_staffing_sequence.xml',
        'data/sf_staffing_cron.xml',
        'data/sf_staffing_report.xml',
        'views/sf_staffing_candidate_views.xml',
        'views/sf_staffing_client_views.xml',
        'views/sf_staffing_need_views.xml',
        'views/sf_staffing_mission_views.xml',
        'views/sf_staffing_contract_views.xml',
        'views/sf_staffing_timesheet_views.xml',
        'views/sf_staffing_menus.xml',
        'views/report_contract.xml',
        'views/report_candidate.xml',
        'views/report_mission_invoice.xml',
        'views/report_activity.xml',
        'views/res_config_settings_views.xml',
    ],
    'installable': True,
    'auto_install': False,
}
