# -*- coding: utf-8 -*-
{
    'name': 'Purchase Requisition Workflow',
    'version': '19.0.1.0.0',
    'category': 'Purchase',
    'summary': 'Purchase requisition with multi-level approval chains, budget checking and vendor suggestion.',
    'description': 'Purchase Requisition Workflow module for Odoo. Purchase requisition with multi-level approval chains, budget checking and vendor suggestion.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock', 'hr', 'purchase'],
    'data': [
        'security/sf_purchase_requisition_security.xml',
        'security/ir.model.access.csv',
        'data/sf_purchase_requisition_sequence.xml',
        'views/purchase_requisition_sf_views.xml',
        'views/requisition_line_views.xml',
        'views/sf_purchase_requisition_menus.xml',
    ],
}
