# -*- coding: utf-8 -*-
{
    'name': 'E-commerce Digital Goods & License Key Delivery',
    'version': '19.0.1.0.0',
    'category': 'Sales',
    'summary': 'Digital products, automatic license key generation, expirable download links and digital delivery tracking',
    'description': 'Sell and deliver digital goods (software licenses, activation keys, e-books, downloads): define digital products, generate unique license keys automatically, create expirable download links, trigger the delivery on order confirmation, track activations and produce PDF delivery and license key certificate reports.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'product', 'sale'],
    'data': [
        'security/sf_digital_delivery_security.xml',
        'security/ir.model.access.csv',
        'data/sf_digital_delivery_sequence.xml',
        'data/sf_digital_delivery_cron.xml',
        'data/sf_digital_delivery_report.xml',
        'views/sf_digital_delivery_product_views.xml',
        'views/sf_digital_delivery_key_views.xml',
        'views/sf_digital_delivery_delivery_views.xml',
        'views/sf_digital_delivery_menus.xml',
        'views/report_digital_delivery.xml',
        'views/report_license_key.xml',
        'views/res_config_settings_views.xml',
    ],
}