# -*- coding: utf-8 -*-
{
    'name': 'Retail Franchise Network Management',
    'version': '18.0.1.0',
    'category': 'Sales',
    'summary': 'Franchise contracts, declared sales, automatic royalty calculation, invoicing and payment tracking',
    'description': 'Manage a retail franchise network: franchise contracts with territory and royalty conditions (fixed or percentage), periodic sales declarations by franchisees, automatic royalty calculation, royalty invoicing (account.move), payment and delay tracking, plus PDF contract and royalty statement reports.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account'],
    'data': [
        'security/sf_franchise_security.xml',
        'security/ir.model.access.csv',
        'data/sf_franchise_sequence.xml',
        'data/sf_franchise_cron.xml',
        'data/sf_franchise_report.xml',
        'views/sf_franchise_contract_views.xml',
        'views/sf_franchise_declaration_views.xml',
        'views/sf_franchise_menus.xml',
        'views/report_franchise_contract.xml',
        'views/report_franchise_declaration.xml',
        'views/res_config_settings_views.xml',
    ],
}