# -*- coding: utf-8 -*-
{
    'name': 'Advanced Asset Depreciation',
    'version': '18.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Multi-method depreciation (straight-line, declining, units) with component accounting and revaluation.',
    'description': 'Advanced Asset Depreciation module for Odoo. Multi-method depreciation (straight-line, declining, units) with component accounting and revaluation.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_asset_depreciation_pro_security.xml',
        'security/ir.model.access.csv',
        'data/sf_asset_depreciation_pro_sequence.xml',
        'views/asset_schedule_line_views.xml',
        'views/asset_revaluation_views.xml',
        'views/sf_asset_depreciation_pro_menus.xml',
    ],
}
