# -*- coding: utf-8 -*-
{
    'name': 'Warehouse Activity Heatmap',
    'version': '19.0.1.0.0',
    'category': 'Inventory',
    'summary': 'Activity heatmap for slotting optimization: pick frequency, travel distance and ABC classification.',
    'description': 'Warehouse Activity Heatmap module for Odoo. Activity heatmap for slotting optimization: pick frequency, travel distance and ABC classification.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_warehouse_heatmap_security.xml',
        'security/ir.model.access.csv',
        'data/sf_warehouse_heatmap_sequence.xml',
        'views/slotting_analysis_views.xml',
        'views/slotting_result_views.xml',
        'views/sf_warehouse_heatmap_menus.xml',
    ],
}
