# -*- coding: utf-8 -*-
{
    'name': 'Shareholder Register & Capital Management (Cap Table)',
    'version': '18.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Shareholders, share classes, capital movements, issued shares, cap table and share certificates',
    'description': 'Shareholder register and capital management: maintain a register of shareholders and share classes with nominal value and authorized shares, record capital movements (buy/sell) with quantity and unit price, compute the amount of each movement, track issued shares per class and total holding per shareholder, validate sell operations against current holdings, post movements to make them immutable, and print PDF reports (cap table and share certificate).',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts'],
    'data': [
        'security/sf_corporate_capital_security.xml',
        'security/ir.model.access.csv',
        'data/sf_corporate_capital_sequence.xml',
        'data/sf_corporate_capital_report.xml',
        'views/sf_shareholder_views.xml',
        'views/sf_share_class_views.xml',
        'views/sf_capital_movement_views.xml',
        'views/sf_corporate_capital_menus.xml',
        'views/report_cap_table.xml',
        'views/report_share_certificate.xml',
    ],
}