# -*- coding: utf-8 -*-
{
    'name': 'Restaurant, Cafe & In-Room Dining',
    'version': '18.0.1.0',
    'category': 'Sales',
    'summary': 'Restaurant and cafe management: tables, reservations, menus, kitchen orders and revenue tracking',
    'description': 'Restaurant and cafe management module for dining rooms: manage tables with states and zones, reservations with capacity control without overbooking, menu categories and items with per-service availability, table orders with kitchen ticket transmission, and daily revenue tracking by service and by table.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'product'],
    'data': [
        'security/sf_restaurant_security.xml',
        'security/ir.model.access.csv',
        'data/sf_restaurant_sequence.xml',
        'data/sf_restaurant_cron.xml',
        'data/sf_restaurant_report.xml',
        'views/sf_restaurant_table_views.xml',
        'views/sf_restaurant_zone_views.xml',
        'views/sf_restaurant_reservation_views.xml',
        'views/sf_restaurant_menu_category_views.xml',
        'views/sf_restaurant_menu_item_views.xml',
        'views/sf_restaurant_order_views.xml',
        'views/sf_restaurant_menus.xml',
        'views/report_kitchen_ticket.xml',
        'views/report_table_bill.xml',
        'views/report_daily_revenue.xml',
        'views/res_config_settings_views.xml',
    ],
}