# -*- coding: utf-8 -*-
{
    'name': 'Intercompany Invoicing Automation',
    'version': '19.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Automated intercompany invoices with multi-book accounting, currency conversion and elimination entries.',
    'description': 'Intercompany Invoicing Automation module for Odoo. Automated intercompany invoices with multi-book accounting, currency conversion and elimination entries.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_intercompany_invoicing_security.xml',
        'security/ir.model.access.csv',
        'data/sf_intercompany_invoicing_sequence.xml',
        'views/ic_sale_views.xml',
        'views/sf_intercompany_invoicing_menus.xml',
    ],
}
