# -*- coding: utf-8 -*-
{
    'name': 'Equipment Rental & Hire Operations',
    'version': '18.0.1.0',
    'category': 'Operations',
    'summary': 'Equipment cards with calendar availability, rental contracts with tiered pricing, out/in inspections, damages and planned maintenance',
    'description': 'Equipment rental and hire operations module for professional rental companies: manage equipment cards with calendar availability, rental contracts with tiered pricing (hour/day/week/month), reservations and availability conflicts, out/in state inspections with damages and penalties, maintenance planning between rentals and automatic invoicing.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account'],
    'data': [
        'security/sf_rental_security.xml',
        'security/ir.model.access.csv',
        'data/sf_rental_sequence.xml',
        'data/sf_rental_report.xml',
        'views/sf_rental_equipment_views.xml',
        'views/sf_rental_contract_views.xml',
        'views/sf_rental_inspection_views.xml',
        'views/sf_rental_maintenance_views.xml',
        'views/sf_rental_menus.xml',
        'views/report_rental_contract.xml',
        'views/report_out_in_ticket.xml',
        'views/report_fleet.xml',
        'views/res_config_settings_views.xml',
    ],
}