# -*- coding: utf-8 -*-
{
    'name': 'Acceptance Sampling & AQL Inspection Plans',
    'version': '19.0.1.0.0',
    'category': 'Quality/Quality',
    'summary': 'Statistical acceptance sampling: AQL inspection plans, lot inspections, defect recording and accept/reject decisions',
    'description': 'Acceptance sampling and AQL inspection plans for quality departments: define sampling plans (inspection level, lot size range, sample size, accept and reject numbers), run lot inspections with automatic plan selection, record defects by severity (critical, major, minor), compute weighted defect scores and automatic accept/reject decisions, release or reject inspected lots, and print the inspection report PDF.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'product', 'stock', 'contacts'],
    'data': [
        'security/sf_aql_sampling_security.xml',
        'security/ir.model.access.csv',
        'data/sf_aql_sampling_sequence.xml',
        'data/sf_aql_sampling_report.xml',
        'views/sf_aql_plan_views.xml',
        'views/sf_aql_inspection_views.xml',
        'views/sf_aql_sampling_menus.xml',
        'views/report_aql_inspection.xml',
        'views/res_config_settings_views.xml',
    ],
}