# -*- coding: utf-8 -*-
{
    'name': 'Electronic Batch Production Records (EBR)',
    'version': '19.0.1.0.0',
    'category': 'Manufacturing/Manufacturing',
    'summary': 'Electronic batch production records: materials, steps, parameters, deviations, QA review and lot release',
    'description': 'Electronic Batch Production Records for regulated manufacturers: create batch records per production campaign, track consumed materials with their lots, document executed steps and operators, record measured parameters with expected values and tolerances, manage deviations (approved/rejected), run a QA review and release workflow with signatures, and print an auditable batch record PDF.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'product', 'stock', 'contacts'],
    'data': [
        'security/sf_batch_records_security.xml',
        'security/ir.model.access.csv',
        'data/sf_batch_records_sequence.xml',
        'data/sf_batch_records_report.xml',
        'views/sf_batch_record_views.xml',
        'views/sf_batch_records_menus.xml',
        'views/report_batch_record.xml',
        'views/res_config_settings_views.xml',
    ],
}