# -*- coding: utf-8 -*-
{
    'name': 'Field Dispatch Board',
    'version': '19.0.1.0.0',
    'category': 'Operations',
    'summary': 'Dispatch board with skills matching, route optimization, SLA timers and mobile check-in/out.',
    'description': 'Field Dispatch Board module for Odoo. Dispatch board with skills matching, route optimization, SLA timers and mobile check-in/out.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_field_dispatch_board_security.xml',
        'security/ir.model.access.csv',
        'data/sf_field_dispatch_board_sequence.xml',
        'views/dispatch_ticket_views.xml',
        'views/sf_field_dispatch_board_menus.xml',
    ],
}
