# -*- coding: utf-8 -*-
{
    'name': 'Events & Conferences Management',
    'version': '18.0.1.0',
    'category': 'Sales',
    'summary': 'Events, sessions, speakers, registrations and ticketing, badge check-in, budget and revenue tracking',
    'description': 'Event management module for organizers, event project managers and ticketing teams: manage events with dates, locations, capacities and budgets, sessions with speakers and rooms, registrations with ticket types and capacity control, badge check-in, and budget and revenue tracking per event.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account'],
    'data': [
        'security/sf_events_security.xml',
        'security/ir.model.access.csv',
        'data/sf_events_sequence.xml',
        'data/sf_events_cron.xml',
        'data/sf_events_report.xml',
        'views/sf_event_views.xml',
        'views/sf_event_session_views.xml',
        'views/sf_event_registration_views.xml',
        'views/sf_event_expense_views.xml',
        'views/sf_events_menus.xml',
        'views/report_event_program.xml',
        'views/report_registration_confirmation.xml',
        'views/report_event_budget.xml',
        'views/report_attendance.xml',
        'views/res_config_settings_views.xml',
    ],
}