# -*- coding: utf-8 -*-
{
    'name': 'Rental Billing & Contracts',
    'version': '19.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Recurring rental billing: contracts, automatic invoicing cycles, proration, deposit management.',
    'description': 'Rental Billing & Contracts module for Odoo. Recurring rental billing: contracts, automatic invoicing cycles, proration, deposit management.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_rental_billing_security.xml',
        'security/ir.model.access.csv',
        'data/sf_rental_billing_sequence.xml',
        'views/rental_contract_views.xml',
        'views/rental_invoice_line_views.xml',
        'views/sf_rental_billing_menus.xml',
    ],
}
