# -*- coding: utf-8 -*-
{
    'name': 'Dock & Shipment Appointment Scheduling',
    'version': '19.0.1.0.0',
    'category': 'Operations',
    'summary': 'Dock registry and truck appointment scheduling with time windows, arrival tracking and no-show detection',
    'description': 'Dock and shipment appointment scheduling for warehouses, distribution centers and 3PL providers: manage receiving/shipping docks, plan truck appointments with time windows, assign docks, track states (scheduled, arrived, docked, completed, no-show, cancelled), record actual arrival/dock/departure times, compute delays and dock durations, detect no-shows automatically with a daily cron, and print the daily schedule PDF.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts'],
    'data': [
        'security/sf_dock_appointments_security.xml',
        'security/ir.model.access.csv',
        'data/sf_dock_appointments_sequence.xml',
        'data/sf_dock_appointments_cron.xml',
        'data/sf_dock_appointments_report.xml',
        'views/sf_dock_views.xml',
        'views/sf_dock_appointment_views.xml',
        'views/sf_dock_appointments_menus.xml',
        'views/report_appointments.xml',
        'views/res_config_settings_views.xml',
    ],
}