# -*- coding: utf-8 -*-
{
    'name': 'Cold Chain Monitoring',
    'version': '18.0.1.0',
    'category': 'Operations',
    'summary': 'Monitor temperature excursions on cold storage sites and transport trips with alerts and reports',
    'description': 'Cold chain monitoring for food, pharma and temperature-sensitive logistics: manage cold storage sites and transport trips with temperature ranges, record temperature readings, detect out-of-range excursions automatically, compute deviation, duration and severity of each excursion, resolve excursions with manager rights, alert on unresolved excursions with a cron, and print the cold chain log PDF report.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail'],
    'data': [
        'security/sf_cold_chain_security.xml',
        'security/ir.model.access.csv',
        'data/sf_cold_chain_sequence.xml',
        'data/sf_cold_chain_cron.xml',
        'data/sf_cold_chain_report.xml',
        'views/sf_cold_site_views.xml',
        'views/sf_cold_trip_views.xml',
        'views/sf_cold_reading_views.xml',
        'views/sf_cold_excursion_views.xml',
        'views/sf_cold_chain_menus.xml',
        'views/report_cold_log.xml',
        'views/res_config_settings_views.xml',
        'views/sf_cold_chain_report_wizard_views.xml',
    ],
}