# -*- coding: utf-8 -*-
{
    'name': 'Trade Promotion Management (TPM)',
    'version': '18.0.1.0.0',
    'category': 'Sales',
    'summary': 'Trade promotion programs, budgets, customer claims, validation workflow and ROI tracking',
    'description': 'Manage trade promotions for FMCG and wholesale: promotion programs with budgets, periods and eligible customers, customer claims / deductions recording and validation, budget consumption tracking, ROI computation per program, daily closure of expired programs and PDF program and claims reports.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account'],
    'data': [
        'security/sf_trade_promotions_security.xml',
        'security/ir.model.access.csv',
        'data/sf_trade_promotions_sequence.xml',
        'data/sf_trade_promotions_cron.xml',
        'data/sf_trade_promotions_report.xml',
        'views/sf_trade_program_views.xml',
        'views/sf_trade_claim_views.xml',
        'views/sf_trade_promotions_menus.xml',
        'views/report_trade_program.xml',
        'views/report_trade_claim.xml',
        'views/res_config_settings_views.xml',
    ],
}