# -*- coding: utf-8 -*-
{
    'name': 'Shop Floor Data Terminal',
    'version': '19.0.1.0.0',
    'category': 'Manufacturing',
    'summary': 'Shop floor terminal for work order tracking, time logging, quantity reporting and scrap entry.',
    'description': 'Shop Floor Data Terminal module for Odoo. Shop floor terminal for work order tracking, time logging, quantity reporting and scrap entry.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_shop_floor_terminal_security.xml',
        'security/ir.model.access.csv',
        'data/sf_shop_floor_terminal_sequence.xml',
        'views/shop_floor_entry_views.xml',
        'views/sf_shop_floor_terminal_menus.xml',
    ],
}
