# -*- coding: utf-8 -*-
{
    'name': 'Business Mail & Correspondence Register',
    'version': '18.0.1.0.0',
    'category': 'Operations',
    'summary': 'Incoming and outgoing correspondence register with routing, response deadlines and registered mail tracking',
    'description': 'Business mail and correspondence register for administrative and legal departments: record inbound and outbound correspondence (direction, date, correspondent, subject, reference, type, registered mail), route it to an internal department and a responsible person, track its status (open, in progress, responded, archived), follow response deadlines with automatic reminders, track registered mail acknowledgments, attach scanned documents, and print PDF reports (correspondence register and correspondence sheet).',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts'],
    'data': [
        'security/sf_correspondence_security.xml',
        'security/ir.model.access.csv',
        'data/sf_correspondence_sequence.xml',
        'data/sf_correspondence_cron.xml',
        'data/sf_correspondence_report.xml',
        'views/sf_correspondence_views.xml',
        'views/sf_correspondence_department_views.xml',
        'views/sf_correspondence_menus.xml',
        'views/report_correspondence_register.xml',
        'views/report_correspondence_sheet.xml',
    ],
}