# -*- coding: utf-8 -*-
{
    'name': 'Quality Inspection Mobile',
    'version': '19.0.1.0.0',
    'category': 'Quality',
    'summary': 'Mobile-first quality inspection checklists with photo capture and non-conformance escalation.',
    'description': 'Quality Inspection Mobile module for Odoo. Mobile-first quality inspection checklists with photo capture and non-conformance escalation.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_quality_inspection_security.xml',
        'security/ir.model.access.csv',
        'data/sf_quality_inspection_sequence.xml',
        'views/inspection_plan_views.xml',
        'views/quality_inspection_views.xml',
        'views/sf_quality_inspection_menus.xml',
    ],
}
