# -*- coding: utf-8 -*-
{
    'name': 'Customer Credit Limits',
    'version': '19.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Automated credit limit enforcement with blocking, escalation workflow and exposure dashboard.',
    'description': 'Customer Credit Limits module for Odoo. Automated credit limit enforcement with blocking, escalation workflow and exposure dashboard.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'account', 'stock'],
    'data': [
        'security/sf_customer_credit_limits_security.xml',
        'security/ir.model.access.csv',
        'data/sf_customer_credit_limits_sequence.xml',
        'views/credit_limit_rule_views.xml',
        'views/credit_exposure_views.xml',
        'views/sf_customer_credit_limits_menus.xml',
    ],
}
