{
    'name': 'Membership & Associations',
    'version': '18.0.1.0.0',
    'category': 'Website',
    'summary': 'Manage members, subscriptions & renewals for associations and NGOs',
    'description': "Complete membership management for Odoo 19. Handles member directories, subscription plans, recurring payments, renewals, and donation tracking. Replaces the removed native membership module.",
    'author': 'SLIMANI Farid',
    'support': 'tech5262@gmail.com',
    'license': 'OPL-1',
    'price': 89.0,
    'currency': 'EUR',
    'depends': ['base', 'mail', 'sale', 'account', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'views/membership_menus.xml',
        'views/membership_plan_views.xml',
        'views/membership_member_views.xml',
        'views/membership_subscription_views.xml',
        'views/membership_payment_views.xml',
        'data/membership_data.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}

