# -*- coding: utf-8 -*-
{
    'name': 'Retail Store Credit & Customer Wallet',
    'version': '19.0.1.0.0',
    'category': 'Sales',
    'summary': 'Customer store credit accounts, reusable credit grants, usage, adjustments, expirations and balances',
    'description': 'Manage store credit / customer wallets for retail: grant reusable credits (reason, amount, expiration), track the available balance per customer, use the credit on sales, record adjustments and cancellations, expire credits with reminders, and produce PDF balance and credit reports. No accounting entries are created.',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'website': 'https://www.smartersaas.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'application': True,
    'installable': True,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'sale'],
    'data': [
        'security/sf_store_credit_security.xml',
        'security/ir.model.access.csv',
        'data/sf_store_credit_sequence.xml',
        'data/sf_store_credit_cron.xml',
        'data/sf_store_credit_report.xml',
        'views/sf_store_credit_account_views.xml',
        'views/sf_store_credit_credit_views.xml',
        'views/sf_store_credit_adjust_wizard_views.xml',
        'views/sf_store_credit_menus.xml',
        'views/report_store_credit_account.xml',
        'views/report_store_credit.xml',
        'views/res_config_settings_views.xml',
    ],
}