{
    'name': 'Sales Auto Workflow',
    'version': '18.0.1.0.0',
    'category': 'Sales',
    'summary': 'Automate quotes, deliveries and invoices with configurable rules',
    'description': "Define rules to automatically confirm sales orders, create deliveries, and generate invoices based on payment method, order type, amount, customer, or custom conditions. Reduce manual steps and accelerate order-to-cash cycle.",
    'author': 'SLIMANI Farid',
    'support': 'tech5262@gmail.com',
    'license': 'OPL-1',
    'price': 49.0,
    'currency': 'EUR',
    'depends': ['base', 'sale', 'stock', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/sale_auto_menus.xml',
        'views/sale_auto_rule_views.xml',
        'views/sale_order_views.xml',
        'data/sale_auto_data.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
