# -*- coding: utf-8 -*-
{
    'name': 'SF Travel Agency',
    'version': '19.0.1.0.0',
    'author': 'Ethan Miller',
    'support': 'tech5262@gmail.com',
    'license': 'OPL-1',
    'price': 62.50,
    'currency': 'EUR',
    'category': 'Sales',
    'summary': 'Manage travel packages, providers, reservations and margin analysis.',
    'description': 'SF Travel Agency manages travel packages, providers, reservations and provider costs with automatic commission and margin computation, capacity control, reminders and reports.',
    'application': True,
    'installable': True,
    'auto_install': False,
    'images': ['static/description/banner.png'],
    'depends': ['base', 'mail', 'contacts', 'account'],
    'data': [
        'security/sf_travel_agency_security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/reports.xml',
        'views/sf_travel_package_views.xml',
        'views/sf_travel_provider_views.xml',
        'views/sf_travel_reservation_views.xml',
        'views/sf_travel_provider_cost_views.xml',
        'views/res_config_settings_views.xml',
        'views/report_reservation_confirmation.xml',
        'views/report_package_itinerary.xml',
        'views/report_reservation_invoice.xml',
        'views/report_margin_report.xml',
        'views/sf_travel_menus.xml',
    ],
}

